name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: check --select I --fix
      - uses: astral-sh/ruff-action@v1
        with:
          args: format
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected after Ruff fix."
          else
            echo "No changes detected."
            exit 0
          fi
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply Ruff fixes"
          git push
